version: "3"
services:
  edgedb:
    image: edgedb/edgedb
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
    volumes:
      - "./dbschema:/dbschema"
      - "edgedb:/var/lib/edgedb/data"
      - "storage:/storage"
    ports:
      - "127.0.0.1:5656:5656"
volumes:
    edgedb:
        external: false
    storage:
        external: false
