# fly.toml file generated for chimu on 2022-04-28T23:03:43-04:00

app = "chimu"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []


[mounts]
source="storage"
destination="/storage"

[env]
  PORT = "8080"
  NODE_ENV = "production"
  EDGEDB_PORT = "5656"


[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
